### ISSUE TITLE
why this error occurs

### ISSUE THREAD

**Issue by muthhu** [NenadPantelic/Handwritten-math-symbols-recognition#1]
print(imgs.getImageVector())
NameError: name 'imgs' is not defined

**Comment by NenadPantelic** [comment]
@muthhu Because it is not defined :slightly_smiling_face: . You didn't mention in which file you found this. You think about this snippet from the https://github.com/NenadPantelic/Handwritten-math-symbols-recognition/blob/master/driver.py
```python
#print(imgs.getImageVector())
#ps.trainModel("./Dataset/extracted_images/")
ps.predict("./TestData/test2.jpg")
```
This code is not clean, but that's not important for your question - the print statement is commented and if you uncomment it, it will say that the imgs var is not defined, cause it's not. You can easily remove that line, I added that probably at some point just for debugging purposes.

**Comment by muthhu** [comment]
Thanks for the reply and I have one more error

Error : No module named 'sklearn.tree.tree'
How can I sort this error?

**Comment by NenadPantelic** [comment]
The initial error was resolved
